### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lixiangnlp** [robertostling/eflomal#1] opened 2017-03-22 10:25 UTC
Hi, I can not compile the eflomal with gcc 4.9.3 using the make command. The error is as follows. I can not find the solution through Google. Do you encounter the error ever?

cc -lm -lrt -lgomp  eflomal.o   -o eflomal
eflomal.o: In function `align._omp_fn.2':
/home/user/work/tool/align/eflomal/eflomal.c:867: undefined reference to `omp_get_num_threads'
/home/user/work/tool/align/eflomal/eflomal.c:867: undefined reference to `omp_get_thread_num'
/home/user/work/tool/align/eflomal/eflomal.c:870: undefined reference to `GOMP_critical_start'
/home/user/work/tool/align/eflomal/eflomal.c:870: undefined reference to `GOMP_critical_end'
eflomal.o: In function `align._omp_fn.1':
/home/user/work/tool/align/eflomal/eflomal.c:848: undefined reference to `omp_get_num_threads'
/home/user/work/tool/align/eflomal/eflomal.c:848: undefined reference to `omp_get_thread_num'
/home/user/work/tool/align/eflomal/eflomal.c:851: undefined reference to `GOMP_critical_start'
/home/user/work/tool/align/eflomal/eflomal.c:851: undefined reference to `GOMP_critical_end'
eflomal.o: In function `main._omp_fn.0':
/home/user/work/tool/align/eflomal/eflomal.c:1007: undefined reference to `omp_get_num_threads'
/home/user/work/tool/align/eflomal/eflomal.c:1007: undefined reference to `omp_get_thread_num'
eflomal.o: In function `align':
/home/user/work/tool/align/eflomal/eflomal.c:848: undefined reference to `GOMP_parallel'
/home/user/work/tool/align/eflomal/eflomal.c:867: undefined reference to `GOMP_parallel'
/home/user/work/tool/align/eflomal/eflomal.c:867: undefined reference to `GOMP_parallel'
/home/user/work/tool/align/eflomal/eflomal.c:848: undefined reference to `GOMP_parallel'
eflomal.o: In function `main':
/home/user/work/tool/align/eflomal/eflomal.c:955: undefined reference to `omp_set_nested'
/home/user/work/tool/align/eflomal/eflomal.c:1007: undefined reference to `GOMP_parallel'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'eflomal' failed
make: *** [eflomal] Error 1

**Comment by robertostling** [comment] 2017-03-22 12:03
This should be fixed by 8eeb225 (the `-fopenmp` option was missing during linking, which is fine on some systems but that could have cause the error for you). If the problem persists please tell me, because I can't reproduce the problem myself.

Thanks for reporting this!

**Closed by robertostling** 2017-03-22 12:03 UTC
